baseurl = "https://example.com/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Chris Prener"
title = "SLU Data Science Seminar"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "DSS Website"
copyright = "Copyright Â© 2016-2017 SLU Data Science Seminar (CC BY 4.0)"
copyrightUrl = "https://creativecommons.org/licenses/by/4.0/"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
share = true
latestpostcount = 5
github = "slu-dss"
email = "prenercg@slu.edu"
linkedin = ""
twitter = "SLUDSS"
facebook = ""
social_banner = "img/banner.png"
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName"

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
